### PR TITLE
Change Self Volume label to Studio Loopback Volume

### PR DESCRIPTION
**Pull request by mikedickey**
Also adding "Studio" to "Master Volume"

Trying to address two issues here. One is that these controls impact the entire studio, versus only YOU. The other is that use of "Self" makes it sound like this is something that one would expect to be able to adjust uniquely for each participant.

Screenshot (333)

Screenshot (332)

### CODE REVIEW

**Comment by JanSto1995** [comment]
That makes sense. I was wondering if 'loopback' might be confusing for people, but the tool tip describes it pretty well so that should clarify for those who don't know.
Screen Shot 2023-05-02 at 4 52 26 PM

**Review by nwang92 — APPROVED** [review]

**Comment by JanSto1995** [comment]
I personally think Self-Volume is more intuitive, I don't think loopback is an intuitive term for an average musician. That being said, I think ppl use our tooltips so that's equally important I guess.

**Comment by mikedickey** [comment]
> I personally think Self-Volume is more intuitive, I don't think loopback is an intuitive term for an average musician. That being said, I think ppl use our tooltips so that's equally important I guess.

We've found that a lot of people are not reading the tooltips, and finding the word "Self" to be misleading. This is leading to a lot of confusion and frustration with volume settings.

**Comment by JanSto1995** [comment]
Interesting, I did not know that. In that case, this PR seems to make sense. Let's see how our clients respond to 'Studio Loopback Volume'.

**Pull request merged**
