### PR TITLE
Feature/new presets

### PR DESCRIPTION
**Pull request by JanSto1995**
New overall soundscape presets, fine-tuned to different scenarios. Note that (almost) all presets come in Mono and Stereo, where Stereo presets are the same as Mono but without the panning link.
This might make it easier for users to understand their choices, as discussed with Andrew F.
Screenshot 2022-08-15 at 16 15 35

### CODE REVIEW

**Comment by nwang92** [comment]
Changing the target merge branch from `main` to `develop`

**Comment by nwang92** [comment]
Added some more supercollider folks on this PR.

One question I have is if my studio is set to use an existing preset (ex: EchoHallPreset), what happens if we merge this in? Since EchoHallPreset is now deleted, will we automatically revert this to some known good preset or do we brick all audio completely?

**Comment by dhing1024** [comment]
> Added some more supercollider folks on this PR.
> 
> One question I have is if my studio is set to use an existing preset (ex: EchoHallPreset), what happens if we merge this in? Since EchoHallPreset is now deleted, will we automatically revert this to some known good preset or do we brick all audio completely?

I was wondering the same thing. I don't think we brick all audio completely. Though we'd want to test to make sure that the web app handles the update gracefully. (One way I think we could do this is by making sure non-existent presets are treated as being equivalent to "Custom")

**Comment by JanSto1995** [comment]
https://user-images.githubusercontent.com/51293620/184897964-32086877-7854-4ce5-8597-d538a67feb60.mp4

**Review by mikedickey — CHANGES_REQUESTED** [review]
We need to run load tests on all these, and use those results to set `max` parameters for all of the mixer configs, to ensure presets will not be able to blow up studios. We also need to ensure that all the new presets provide good coverage for our range of studio sizes, and that this update will not break any existing configs (users should have to "opt in" to switch to them).

**Comment by JanSto1995** [comment]
putting this on hold until finished testing and setting `max` parameters

**Pull request closed without merging**
