### PR TITLE
Feature/presets and impulse responses

### PR DESCRIPTION
**Pull request by mikedickey**

### CODE REVIEW

**Comment by JanSto1995** [comment]
Ran into a merge conflict due to our recent changes ([86](url) and [85](url)) but resolved the conflicts with the kind help from @mattahorton . Merging should now be able be performed automatically, if approved. Let me briefly double-check if _feature/PresetsANDImpulseResponses_ still works fine and get back to you in a sec

**Comment by JanSto1995** [comment]
After double-checking all presets under _feature/PresetsANDImpulseResponses_, all works as expected. I believe we're good to go.

**Comment by JanSto1995** [comment]
@mikedickey @dhing1024

**Review by dhing1024 — APPROVED** [review]
Did a quick scan of all the changes in this PR. I think this looks good to go.

**Pull request merged**
